# Generated by Django 3.2.4 on 2021-06-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210622_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='day_num',
            field=models.IntegerField(null=True),
        ),
    ]
