# Generated by Django 3.2.4 on 2021-07-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210719_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentslesson',
            name='freezed',
            field=models.BooleanField(default=False),
        ),
    ]
